print("Hello")
print("What is your name?")
MyName = input()
print("it is good to meet you, " + MyName)
print("The length of your name is: ")
print(len(MyName))
print("What is your age?")
myAge = input()
print('You will be ' + str(int(myAge) +1) + ' in a year.')
